# Numpy et tableau de contingence

Un exercice classique : écrire le calcul du $\chi_2$ d'un tableau de contingence sans écrire explicitement une boucle. numpy s'en chargera. A suivre jusqu'à ce que vous n'en ayez plus besoin.

In [46]:
import numpy as np

A = np.array([[0, 1, 2, 3], [4, 5, 6, 7]], dtype=float)
A

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]])

In [48]:
A.sum(axis=1, keepdims=1)

array([[ 6.],
       [22.]])

In [49]:
A + A.sum(axis=1, keepdims=1)

array([[ 6.,  7.,  8.,  9.],
       [26., 27., 28., 29.]])

In [45]:
A.sum(axis=0, keepdims=1)

array([[ 4,  6,  8, 10]])

In [54]:
B = np.zeros(A.shape, dtype=A.dtype)
N2 = A.sum() ** 2
L = A.sum(axis=1)
C = A.sum(axis=0)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        B[i, j] = A[i, j] - L[i] * C[j] / N2
B

array([[-0.03061224,  0.95408163,  1.93877551,  2.92346939],
       [ 3.8877551 ,  4.83163265,  5.7755102 ,  6.71938776]])

In [56]:
A - A.sum(axis=1, keepdims=1) * A.sum(axis=0, keepdims=1) / A.sum() ** 2

array([[-0.03061224,  0.95408163,  1.93877551,  2.92346939],
       [ 3.8877551 ,  4.83163265,  5.7755102 ,  6.71938776]])

In [57]:
L = A.sum(axis=1, keepdims=1)
C = A.sum(axis=0, keepdims=1)
L.shape, C.shape

((2, 1), (1, 4))

In [58]:
L * C

array([[ 24.,  36.,  48.,  60.],
       [ 88., 132., 176., 220.]])

In [59]:
C * L

array([[ 24.,  36.,  48.,  60.],
       [ 88., 132., 176., 220.]])

In [61]:
L @ C

array([[ 24.,  36.,  48.,  60.],
       [ 88., 132., 176., 220.]])